apiVersion: apps/v1
kind: Deployment
metadata:
  name: cicd-test
  labels: 
    app: cicd-test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cicd-test
  template:
    metadata:
      labels:
        app: cicd-test
    spec:
      containers:
      - name: cicd-container
        image: wotkddl21/cicd-test
        ports:
        - containerPort: 3000
        env:
        - name: DATE
          value: '2021-02-16'
      imagePullSecrets:
        - name: my-secret
